name: Main

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-2
  AWS_ACCOUNT_ID: 692859929663
  AWS_IAM_ROLE: arn:aws:iam::692859929663:role/cicd-github-actions
  ECR_REPOSITORY: default
  CONTAINER_NAME: student-ui

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to EC2.
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    runs-on: self-hosted
    env: 
      AWS_REGION: ${{ env.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ env.AWS_ACCOUNT_ID }}
    steps:
      - name: Pull image from Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
          docker pull ${{ steps.build-image.outputs.image }}
      - name: Run docker container
        run: |
          docker rm -f student-ui
          docker run -d -p 3000:3000 --name student-ui integrationninjas/nextjs-app
